### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by adrianna16** [OpenSZN39/web-design-2-independent-project#1]
- There is some overlapping text onto images, im not sure if you already have everything in a grid but that may fix the problem.
- When browsing on a mobile the content is too big for the screen so it scrolls from left to right.
- Everything is good for performance speed.
- I really like your website so far! it looks legit, good job!

**Comment by OpenSZN39** [comment]
Thanks for the feedback @adrianna16 ! I did end up adjusting those text and size issues for mobile use, so they should no longer be an issue!

Thanks!

**Comment by adrianna16** [comment]
No problem! Thank you for your feedback as well!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
