### ISSUE TITLE
Slight performance speed issues on mobile

### ISSUE THREAD

**Issue by OpenSZN39** [OpenSZN39/web-design-2-independent-project#4]
![image](https://user-images.githubusercontent.com/77280572/145906433-6ca338e0-7a78-42ef-b25e-89c37ee320f3.png)

![image](https://user-images.githubusercontent.com/77280572/145906456-12d1958c-12c2-4454-a1c5-92b3267646fc.png)

Double check issue with font code and its connection to lower performance in mobile tests.

@thatkidmadrid I don't know if you would have any insight on this or if it is big enough to bother with?

**Comment by thatkidmadrid** [comment]
Sorry I'm just getting to this now - it was buried with other issues.
There's an inline display=swap in the url but it wouldn't hurt to also include it in your css

wherever you set the font in your css you will want to also include `font-display: swap` to help remove any blocking that's happening

**Comment by OpenSZN39** [comment]
All fixed thanks for the suggestion!
