### ISSUE TITLE
Markbot .bak image re-smushing

### ISSUE THREAD

**Issue by OpenSZN39** [OpenSZN39/web-design-2-independent-project#6]
@thatkidmadrid

My markbot is giving me an error where it is asking me to smush the .bak files that are created when I optimize my images in File Optimizer.

![image](https://user-images.githubusercontent.com/77280572/146107867-ee10508d-158e-4601-aeb1-6fce0e4cb346.png)

Any thoughts on a solution here? I don't know how to optimize this better.

**Comment by thatkidmadrid** [comment]
you're getting .jpg.bak files from imageoptim? or are you using another tool?

**Comment by OpenSZN39** [comment]
I'm using windows so I'm using File Optimizer, the program Thomas suggested in the images lesson.

![image](https://user-images.githubusercontent.com/77280572/146109307-bcd37afe-9466-4ba3-b36c-83b04449404f.png)

**Comment by thatkidmadrid** [comment]
ok, so I'm not super familiar with that program but there must be a way to export the non-.bak files. It must be creating a backup of the original files in case something goes from with the optimized files. I'll do some research on my end

**Comment by OpenSZN39** [comment]
ok. I just know I didn't get this error during the images assignment. Although I assume Markbot wasn't looking for this at that time.

**Comment by thatkidmadrid** [comment]
So I read through the documentation on their site and it says they create the backups while the optimization is running, so maybe it wasn't finished running when you grabbed the .bak files? you can give it another shot and if that doesn't work let me know and I'll run them through markbot on my end

**Comment by thatkidmadrid** [comment]
You can remove the .bak files
I can see it in your images folder now, it optimized the images already but created the .bak files too
The images with the original name and file extensions are already smushed

**Comment by OpenSZN39** [comment]
Oh yeah. duh. ok I should have just done that. It's fine now.

I have another issue as well but ill make a new issue for it.
