### ISSUE TITLE
Skip links in Markbot

### ISSUE THREAD

**Issue by OpenSZN39** [OpenSZN39/web-design-2-independent-project#7]
@thatkidmadrid

For the skip links, Markbot clearly wants them, but my site isn't really set up in a way that skip links make sense. Do you have any suggestions as a work around for this?

![image](https://user-images.githubusercontent.com/77280572/146110566-19bc3429-f253-45b5-b44f-889af00fa03b.png)

**Comment by thatkidmadrid** [comment]
if you have a navigation and a main area then you can definitely support skip links. They don't need to mess up your layout - you can hide them by default and then reveal them when they have keyboard focus. This is why markbot is saying to have it as the first child of the body tag so when you hit tab on page load, it goes directly to your skip links.

Here is the cheatsheet with some tips for how to set it up and very basic styling to have them hide by default and reveal on focus: https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/#html-semantics

**Comment by OpenSZN39** [comment]
Awesome thank you, the code has been added.
